name: ğŸ§ª Testing

on:
  workflow_run:
      workflows: ["ğŸ§¹ Linting"]
      types:
        - completed
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    # ensure tests only run after linting passes
    # (requires workflow_run trigger, see below)
    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v5
      - name: ğŸ” Read Python version from environment.yml
        id: python_version
        run: |
          PYTHON_VERSION=$(grep '^- python=' ./requirements/environment.yml | cut -d'=' -f2 | xargs)
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
      - name: ğŸ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: $GITHUB_ENV

      - name: ğŸ“¦ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ğŸ§ª Run Pytest
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src tests/ | tee pytest-coverage.txt

      - name: ğŸ“Š Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.1.59
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
